# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: BelfastFP
#subtitle:
subtitle: Functional Programming User Group

# Title attribute of HTML Page, uses 'name' from above if empty
title:

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: Belfast Functional Programming Meetup
    keywords: belfast, belfastfp, functional programming
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://belfastfp.github.io/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: ''

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: 'UA-'
    cookieconsent: true
    anonymizeip: true


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "https://pbs.twimg.com/profile_images/1235917452694958080/cvyEYwlG_400x400.jpg"

#avatar: "images/jonathan_doe.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - mailinglist:
      name: Meetup Mailing List
      show: true
      href: https://tinyletter.com/belfastfp
      icon: fas fa-chalkboard-teacher
  - twitter:
      name: Twitter
      show: true
      href: https://twitter.com/belfastfp
      icon: fab fa-twitter
  - github:
      name: GitHub
      show: true
      href: https://github.com/belfastfp
      icon: fab fa-github
  - blog:
      name: Blog
      show: false
      href: http://host.domain/your_blog
      icon: fas fa-book-open
  - email:
      name: Email
      show: true
      href: mailto:belfastkats@gmail.com
      icon: fas fa-envelope


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
extra_html: >
  <p>Monthly meetup in Belfast for developers with an interest in <strong>Functional programming</strong>.</p>
  <p>Recently we have move away from Meetup.com as our platform.</p>
  <p>We run our Meetups and Events by directly communicating with our members via our <strong>Mailing List</strong>.</p>
  <div class="d-flex justify-content-center">
    <form action="https://tinyletter.com/belfastfp" method="post" target="popupwindow" onsubmit="window.open('https://tinyletter.com/belfastfp', 'popupwindow', 'scrollbars=yes,width=800,height=600');return true">
      <div class="form-group">
        <input placeholder="Your Email" type="text" class="form-control form-control" name="email" id="tlemail" />
      </div>
      <input type="hidden" value="1" name="embed"/>
      <button type="submit" class="btn btn-light" value="Subscribe">Join the Group</button>
    </form>
  </div>
#EOF
